### ISSUE TITLE
Uses outdated? Basemap

### ISSUE THREAD

**Issue by Fran89** [nikosT/scisola#2]
The version of Basemap that this is using is clashing with the matplotlib. Just in case anyone else encounters this the fix is here:

https://stackoverflow.com/questions/50691151/axessubplot-object-has-no-attribute-get-axis-bgcolor

This is just an FYI if anyone else encounters this error, feel free to close it.

Thanks for making this free and open source. Even more importantly keeping it updated! You're much appreciated.

**Comment by nikosT** [comment]
@Fran89, thank you for the feedback! Scisola is guaranteed to run with the suggested libraries on the installation page. Otherwise, it might not fulfill the necessary methods. You are welcome though to dockerize the software and make  a PR for it.
